name: NanoPi-R2S RK3328 OpenWrt 21.02 Build

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          curl -fsSL https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
  
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v21.02 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          cp ../rk3328.xml ../code/.repo/manifests/rk3328.xml
          repo sync -c --no-clone-bundle -j8

      - name: Install Extra Packages
        run: |
          cd code/friendlywrt/package

          git clone https://github.com/rufengsuixing/luci-app-adguardhome

          git clone https://github.com/jerrykuku/lua-maxminddb.git
          git clone https://github.com/jerrykuku/luci-app-vssr.git

          rm -rf lean/luci-theme-argon
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git

          svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash
          
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/luci-app-passwall
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/tcping
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/ssocks
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/trojan-plus
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/trojan-go
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/naiveproxy
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/brook
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/chinadns-ng
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/xray-core
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/xray-plugin
          
          svn co https://github.com/songchenwen/nanopi-r2s/trunk/luci-app-r2sflasher
          
          svn co https://github.com/pymumu/smartdns/trunk/package/openwrt smartdns
          svn co https://github.com/pymumu/luci-app-smartdns/branches/lede luci-app-smartdns
          
          svn co https://github.com/lisaac/luci-app-dockerman/trunk/applications/luci-app-dockerman
          
          git clone https://github.com/jerrykuku/luci-app-jd-dailybonus.git
          git clone https://github.com/NateLol/luci-app-oled
        
      - name: Install Clash Binaries
        run: |
          cd code/friendlywrt/package/base-files/files
          mkdir -p etc/openclash/core
          # for updates, go to: https://github.com/Dreamacro/clash/releases
          wget -qO- https://github.com/Dreamacro/clash/releases/download/v1.9.0/clash-linux-armv8-v1.9.0.gz | gunzip -c > etc/openclash/core/clash
          # for updates, go to: https://github.com/vernesong/OpenClash/releases/tag/TUN-Premium
          wget -qO- https://github.com/vernesong/OpenClash/releases/download/TUN-Premium/clash-linux-armv8-2022.01.03.gz | gunzip -c > etc/openclash/core/clash_tun
          # for updates, go to: https://github.com/vernesong/OpenClash/releases/tag/TUN
          wget -qO- https://github.com/vernesong/OpenClash/releases/download/TUN/clash-linux-armv8.tar.gz | tar xOvz > etc/openclash/core/clash_game
          chmod +x etc/openclash/core/clash*

      - name: Update Target.mk
        run: |
          cd code/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk

      - name: Update Feeds		
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds update -a		
          ./scripts/feeds install -a
          
      - name: Patch Kernel
        run: |
          cd code/kernel/
          #git apply ../../patches/001-add-full_cone_nat.patch

      - name: Custom Configure Files
        run: |
          rm -f code/friendlywrt/.config*
          cp r2s-rk3328-config code/configs/config_rk3328

      - name: Set Default Values
        run: |
          cd code/friendlywrt
          sed -i '/uci commit luci/i\uci set luci.main.mediaurlbase=/luci-static/argon' package/lean/default-settings/files/zzz-default-settings
           
      - name: Install UPX
        run: |
          ln -s /usr/bin/upx-ucl code/friendlywrt/staging_dir/host/bin/upx

      - name: Build OpenWrt
        run: |
          cd code
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk

      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -o 100663296 $lodev code/out/*.img
          #sudo mkfs -t ext4 $lodev
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount $lodev /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/

          cp code/out/*.img.zip ./artifact/
          cp code/friendlywrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S RK3328 v21.02
          path: ./artifact/
